### ISSUE TITLE
Not triggering CircleCI

### ISSUE THREAD

**Issue by taktran** [tschaub/gh-pages#298]
How would you recommend deploying when you have CircleCI set up so that the `gh-pages` branch isn't built?

I have a `ignore` statement in my `.circleci/config.yml` file, but this is removed when I run `npm run deploy`. This means CircleCI always fails on build when `gh-pages` is updated.

**Comment by lopopolo** [comment]
@taktran you can tell CircleCI to skip building a commit with the commit message. This is my gh-pages deploy step in one of my projects:

```yaml
- run:
    name: Deploy docs to gh-pages branch
    command: yarn run gh-pages --message "[skip ci] generate docs" --dist target/doc
```
