### ISSUE TITLE
How to use with GitHub Actions?

### ISSUE THREAD

**Issue by RehanSaeed** [tschaub/gh-pages#345]
I have an npm script like this in `packages.json`:

```json
"deploy": "gh-pages --branch master --dist dist --repo"
```

Then in my GitHub Actions `build.yml` I have the following step:

```yml
- name: 'Deploy'
  run: npm run deploy -- https://${{ secrets.GITHUB_TOKEN }}@github.com/foo/bar.github.io.git
  shell: bash
```

Note that adding any arguments after `npm run deploy --` get double quoted, so I moved `--repo` into the `packages.json` file.

However, this errors with:

```
> gh-pages --branch master --dist dist --repo "https://***@github.com/foo/bar.github.io.git"


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'runneradmin@fv-az31.(none)')
```

**Comment by seveibar** [comment]
You'll want to set the user properly and make sure you have the correct credentials. Try using the user flag like this:

`npx gh-pages -d -u "github-actions-bot <support+actions@github.com>"`

Make sure you have the "env" key for the `GITHUB_TOKEN`. All together, the step should look like this:

```yaml
- name: Publish github pages
  run: |
    npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Props go to @nchaulet for writing a [github action that demonstrated this here](https://github.com/nchaulet/github-action-gh-pages/blob/master/entrypoint.sh)

**Comment by RehanSaeed** [comment]
That didn't seem to work for me. I tried without `git remote set-url`:

```

Run npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
  npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
The syntax of the command is incorrect.
##[error]Process completed with exit code 1.
```

And with:

```
Run git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
  npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
The syntax of the command is incorrect.
##[error]Process completed with exit code 1.
```

Here is my full yaml:

```yml
    - name: 'Deploy'
      if: github.event_name != 'pull_request'
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
        npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by seveibar** [comment]
You'll have to adjust the syntax for the environment varoable substitution for windows I think

On Sat, Apr 4, 2020, at 9:29 AM, Muhammad Rehan Saeed wrote:
> 

> That didn't seem to work for me. I tried without `git remote set-url`:

> `
Run npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
  npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
The syntax of the command is incorrect.
##[error]Process completed with exit code 1.
`
> And with:

> `Run git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
  npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
The syntax of the command is incorrect.
##[error]Process completed with exit code 1.
`
> Here is my full yaml:

>     - name: 'Deploy'
      if: github.event_name != 'pull_request'
      run: |
>         git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
>         npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
>       shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by seveibar** [comment]
Here's my repositories github action for reference: https://github.com/UniversalDataTool/universal-data-tool/blob/master/.github/workflows/release-on-master.yml

**Comment by RehanSaeed** [comment]
Switched to ubuntu and it works. thanks!

**Comment by igormcsouza** [comment]
> You'll want to set the user properly and make sure you have the correct credentials. Try using the user flag like this:
> 
> `npx gh-pages -d -u "github-actions-bot <support+actions@github.com>"`
> 
> Make sure you have the "env" key for the `GITHUB_TOKEN`. You may need to set the remote url (I had to do this because of my checkout action). All together, the step should look like this:
> 
> ```yaml
> - name: Publish github pages
>   run: |
>     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/USER_OR_ORG/REPO.git
>     npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
>   env:
>     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> Props go to @nchaulet for writing a [github action that demonstrated this here](https://github.com/nchaulet/github-action-gh-pages/blob/master/entrypoint.sh)

thanks it saved me so much!! hahaha

**Comment by lukesmurray** [comment]
complete working example

```yml
name: "Deployment"
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Get yarn cache directory path # get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2 # cache yarn
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "Install Dependencies"
        run: yarn
      - name: "Github Pages Deployment"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -u "github-actions-bot <support+actions@github.com>"
        if: ${{ github.ref == 'refs/heads/master' }} # only deploy master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Assumes that the following deploy scripts exist in package.json

```json
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build",

```
