### ISSUE TITLE
could not read Username in CI environment

### ISSUE THREAD

**Issue by Einere** [tschaub/gh-pages#359]
## Local Environment
OS : macOS Catalina 10.15.5

## Description
I'm try to use `gh-pages -d build` in GitHub Actions environment.
so, i make workflow file `CICD.yml`
```yml
name: CICD

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and deploy
        env:
          MY_EMAIL: kjwsx23@gmail.com
          MY_NAME: Einere
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          yarn install
          yarn deploy
```
and i add `"deploy": "gh-pages -d build"` script to `package.json`.

when merge PR, It failed with below error. [link](https://github.com/Einere/homepage/runs/726678791?check_suite_focus=true)
```shell
$ gh-pages -d build
fatal: could not read Username for 'https://github.com': No such device or address

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

so, i add setting command to `CICD.yml`
```yml
...
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME
          gh-pages -u ${MY_NAME} <${MY_EMAIL}>
          yarn install
          yarn deploy
...
```
and below error ocurred. [link](https://github.com/Einere/homepage/runs/726703149?check_suite_focus=true)
```shell
/home/runner/work/_temp/dfd83a59-a8e0-41ea-8cec-0b2d6b28f99d.sh: line 5: syntax error near unexpected token `newline'
##[error]Process completed with exit code 2.
```

how can i set Username in CI environment?

### note
using `yarn deploy` in local terminal, it deploy successfully.
